[build-system]
requires = [
    "setuptools >= 35.0.2",
    "setuptools_scm >= 2.0.0, <3"
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """

[tox]
envlist = py37

[testenv]
deps = pytest
       numpy
       scipy
       nose

commands =
    nosetests iadpython/test_fresnel.py
    nosetests iadpython/test_quadrature.py
    nosetests iadpython/test_redistribution.py
    nosetests iadpython/test_start.py
    nosetests iadpython/test_layer.py
    nosetests iadpython/test_boundary.py
    nosetests iadpython/test_combo.py
    nosetests iadpython/test_ur1_uru.py
"""