[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.check-manifest]
ignore = ["release.txt",
          "todo.txt",
          "Makefile",
          ".readthedocs.yaml",
          ".testignore",
          "docs/*",
          "tests_iadc/*"]


[tool.ruff]
line-length = 100
ignore = ["F403", "F841"]
exclude =['.git', '__pycache__', 'docs']
