[build-system]
requires = [
    "setuptools >= 35.0.2",
    "setuptools_scm >= 2.0.0, <3"
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """

[tox]
envlist = py37

[testenv]
deps = pytest
       numpy
       scipy

commands =
    python -m unittest iadpython/test_fresnel.py
    python -m unittest iadpython/test_quadrature.py
    python -m unittest iadpython/test_redistribution.py
    python -m unittest iadpython/test_start.py
    python -m unittest iadpython/test_layer.py
    python -m unittest iadpython/test_boundary.py
    python -m unittest iadpython/test_combo.py
    python -m unittest iadpython/test_ur1_uru.py
    python -m unittest iadpython/test_iadc.py
    python -m unittest iadpython/test_time.py
"""